[project]
name = "custom-tfnsw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "axbouf", email = "axbouf@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
]

[project.scripts]
custom-tfnsw = "custom_tfnsw:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
