[project]
name = "custom-tfnsw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "axbouf", email = "axbouf@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "dotenv>=0.9.9",
    "google>=3.0.0",
    "gtfs-realtime-bindings>=2.2.0",
    "protobuf>=7.36.1",
    "requests>=2.34.2",
]

[project.scripts]
custom-tfnsw = "custom_tfnsw:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
